### ISSUE TITLE
crashing on launch

### ISSUE THREAD

**Issue by ofZach** [HalfdanJ/ofxARCore#12]
pixel 2 xl phone - running android 8.1
installed arcore: adb install -r -d arcore-preview2.apk 

adb shell 'pm list packages -f' | grep tango
**package:/system/app/TangoCore/TangoCore.apk=com.google.tango**

when app launches: 

```
02-13 04:37:42.560 7953-7953/? E/Tango: Java version of Tango Service not found, falling back to tangoservice_d.
02-13 04:37:42.560 7953-7953/? E/zygote: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(android.content.Context) (tried Java_com_google_atap_tango_TangoJNINative_Initialize and Java_com_google_atap_tango_TangoJNINative_Initialize__Landroid_content_Context_2)
02-13 04:37:42.560 7953-7953/? D/AndroidRuntime: Shutting down VM
02-13 04:37:42.562 7953-7953/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: cc.openframeworks.arcoreexample, PID: 7953
                                                 java.lang.UnsatisfiedLinkError: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(android.content.Context) (tried Java_com_google_atap_tango_TangoJNINative_Initialize and Java_com_google_atap_tango_TangoJNINative_Initialize__Landroid_content_Context_2)
                                                     at com.google.atap.tango.TangoJNINative.Initialize(Native Method)
                                                     at com.google.atap.tangoservice.Tango.<init>(Tango.java:385)
                                                     at com.google.ar.core.TangoWrapper.createInstance(TangoWrapper.java:32)
                                                     at com.google.ar.core.Session.bindTangoService(Session.java:425)
                                                     at com.google.ar.core.Session.resume(Session.java:153)
                                                     at cc.ofxarcorelib.ofxARCoreLib$1.run(ofxARCoreLib.java:77)
                                                     at android.os.Handler.handleCallback(Handler.java:790)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:164)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

is this a arcore mismatch or something else?

**Comment by ofZach** [comment]
the crashing goes away if I install arcore-preview.apk, maybe arcore-preview2.apk isn't installed or needs to be installed on top of arcore-preview.apk ?

It's not super clear to me how the arcore-preview.apk and arcore-preview2.apk are supposed to be used / installed.
